name: OnBoarding Library CI Pipelines

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/Checkout@v4

      - name: Run Lint Check
        run: ./gradlew lintDebug --stacktrace

      - name: Upload test Report
        uses: actions/upload-artifact@v4
        with:
          name: lint_report
          path: onBoardingLibrary/build/reports/lint-results-debug.html

  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Tests
        run: ./gradlew test --stacktrace

      - name: Upload test Report
        uses: actions/upload-artifact@v4

        with:
          name: unit_test_report
          path: onBoardingLibrary/build/reports/tests/testDebugUnitTest
  publish:
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Publish to maven
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
